version: '2'
services:

  web:
    restart: always
    build: .
#    command: /bin/bash -c "pip install -r requirements.txt; python manage.py migrate; python manage.py collectstatic --no-input"
    container_name: web_proven_service
    env_file: .env
    volumes:
      - ./src:/src
      - ./src/media:/media/
    ports:
      - "8001:8001"
    depends_on:
      - postgresql

  postgresql:
    image: postgres:10
    container_name: postgresql_proven_service
    env_file: .env
    volumes:
      - db-proven_service:/var/lib/postgresql/data/pgdata
    ports:
      - "5434:5432"


volumes:
  db-proven_service:
